version: "3.9"
services:
  jgdokrouterserver:
    image: jgdokrouterserver:${TAG}
    container_name: jgdokrouterserver
    hostname: jgdokrouterserver
    volumes:
      - "./volumes/jgdokrouterserver/aspnetKeys:/root/.aspnet/DataProtection-Keys"
      - "./volumes/jgdokrouterserver/configurations/appsettings.json:/app/appsettings.json"
      - "./volumes/jgdokrouterserver/logs:/logs"
 
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/nginx/configurations/nginx.conf:/etc/nginx/nginx.conf"
      - "./volumes/nginx/configurations/jgdokrouterserver-nginx.conf:/etc/nginx/jgdokrouterserver-nginx.conf"
      - "./volumes/nginx/configurations/proxy_params:/etc/nginx/proxy_params"
      - "./volumes/nginx/logs:/logs"
      - "./volumes/nginx/ssl:/etc/nginx/ssl"
    depends_on:
      - jgdokrouterserver
    
