version: "3.9"
services:
  jgdokrouterserver:
    image: jgdokrouterserver:${TAG}
    container_name: jgdokrouterserver
    hostname: jgdokrouterserver
    volumes:
      - "./volumes/jgdokrouterserver/aspnetKeys:/root/.aspnet/DataProtection-Keys"
      - "./volumes/jgdokrouterserver/configurations/appsettings.json:/app/appsettings.json"
      - "./volumes/jgdokrouterserver/logs:/logs"